package sample;

import sample.argouml81.ArgoUML81;
import sample.swarm52.Node;
import sample.swarm52.Pick;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'juan' at '3/18/20 8:43 AM' with Gradle 2.10
 *
 * @author juan, @date 3/18/20 8:43 AM
 */
public class Main {
    public static void main(String[] args) {
        int intArg = Integer.parseInt(args[0]);

        new SampleClass(intArg).execute();
        new ArgoUML81().execute();
        new Pick(new Node("something"));
    }
}
